SET search_path TO public;

DROP TRIGGER IF EXISTS on_change ON accounts;
DROP TRIGGER IF EXISTS on_change ON clients;
DROP TRIGGER IF EXISTS on_change ON credits;
DROP TRIGGER IF EXISTS on_change ON debits;
DROP TRIGGER IF EXISTS on_change ON topups;
DROP TRIGGER IF EXISTS on_change ON transactions;
DROP TRIGGER IF EXISTS on_change ON owners;
DROP TRIGGER IF EXISTS on_change ON wallets;

CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON accounts
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON clients
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON credits
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON debits
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON topups
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON transactions
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON owners
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();
CREATE TRIGGER on_change AFTER INSERT OR UPDATE OR DELETE ON wallets
  FOR EACH ROW EXECUTE PROCEDURE lynx.log_changes();

