SET search_path TO public;

DROP TRIGGER IF EXISTS log_changes ON accounts;
DROP TRIGGER IF EXISTS log_changes ON clients;
DROP TRIGGER IF EXISTS log_changes ON credits;
DROP TRIGGER IF EXISTS log_changes ON debits;
DROP TRIGGER IF EXISTS log_changes ON topups;
DROP TRIGGER IF EXISTS log_changes ON transactions;
DROP TRIGGER IF EXISTS log_changes ON owners;
DROP TRIGGER IF EXISTS log_changes ON wallets;

CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON accounts
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON clients
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON credits
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON debits
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON topups
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON transactions
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON owners
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();
CREATE TRIGGER log_changes AFTER INSERT OR UPDATE OR DELETE ON wallets
  FOR EACH ROW EXECUTE PROCEDURE private.log_changes();

