# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#

noverify = [
  ".go",
  ".build",
  "conf",
  "db",
  "log",
  "messages",
  "public",
  "test-results",
  "tmp",
  "wiki"
]

required = [
  "github.com/revel/cmd/revel",
  "github.com/revel/modules/testrunner/app"
]

[[override]]
  name = "github.com/xeonx/timeago"
  branch = "master"

[[override]]
  name = "github.com/revel/log15"
  branch = "master"

[[override]]
  name = "github.com/revel/cmd"
  version = "0.19.0"

[[override]]
  name = "github.com/revel/revel"
  version = "0.19.0"
