# Gopkg.toml
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#

noverify = [
  "conf",
  "db",
  "log",
  "messages",
  "public",
  "test-results",
  "tmp",
  "wiki"
]

required = [
  "github.com/revel/cmd/revel",
  "github.com/revel/modules/static",
  "github.com/revel/modules/static/app/controllers",
  "github.com/revel/modules/testrunner",
  "github.com/revel/modules/testrunner/app",
  "github.com/revel/modules/testrunner/app/controllers"
]

[[override]]
  name = "github.com/xeonx/timeago"
  branch = "master"

[[override]]
  name = "github.com/revel/log15"
  branch = "master"

[[constraint]]
  name = "github.com/revel/cmd"
  version = "0.19.0"

[[constraint]]
  name = "github.com/revel/modules"
  version = "0.19.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "0.19.0"

[prune]
  go-tests = true
  unused-packages = true
